#!/usr/bin/env bash
#
# Render the user-level agent instruction files from agents/core.md and one header per harness.
#
#   agents/render.sh          write every output listed in output_map below
#   agents/render.sh --check  render into a temp dir and diff against the committed outputs;
#                             exit 1 if any output is stale or missing
#
# Each output is: the header's frontmatter (if it starts with one), a one-line banner naming the
# sources, the rest of the header, one blank line, then core.md. The outputs are committed and
# deployed by bootstrap.sh's ordinary rsync; never edit them by hand.

set -euo pipefail

agents_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_dir="$(dirname "${agents_dir}")"

# Header file in agents/ : output path relative to the repo root.
output_map=(
	"claude-code.md:home/.claude/CLAUDE.md"
	"codex.md:home/.codex/AGENTS.md"
	"opencode.md:config/opencode/AGENTS.md"
	"cursor.md:home/.cursor/rules/00-environment.mdc"
	"pi.md:home/.pi/agent/AGENTS.md"
)

# Define Function =render_one= — print one rendered output to stdout.
# Args: <header file name in agents/>
render_one() {
	local header="${1}"
	local header_path="${agents_dir}/${header}"
	local banner="<!-- Generated by agents/render.sh from agents/${header} and agents/core.md. -->"

	local line
	local first=1
	local in_frontmatter=0
	local banner_done=0

	while IFS= read -r line || [[ -n "${line}" ]]; do
		if [[ "${first}" -eq 1 ]]; then
			first=0
			if [[ "${line}" == "---" ]]; then
				in_frontmatter=1
				printf '%s\n' "${line}"
				continue
			fi
		fi

		if [[ "${in_frontmatter}" -eq 1 ]]; then
			printf '%s\n' "${line}"
			[[ "${line}" == "---" ]] && in_frontmatter=0
			continue
		fi

		if [[ "${banner_done}" -eq 0 ]]; then
			printf '%s\n' "${banner}"
			banner_done=1
		fi
		printf '%s\n' "${line}"
	done <"${header_path}"

	if [[ "${in_frontmatter}" -eq 1 ]]; then
		echo "render.sh: ${header}: frontmatter is not closed" >&2
		return 1
	fi
	[[ "${banner_done}" -eq 0 ]] && printf '%s\n' "${banner}"

	printf '\n'
	cat "${agents_dir}/core.md"
}

# Define Function =render_all= — render every output under a target root.
# Args: <root directory>
render_all() {
	local root="${1}"
	local entry header out tmp

	for entry in "${output_map[@]}"; do
		header="${entry%%:*}"
		out="${root}/${entry#*:}"
		mkdir -p "$(dirname "${out}")"
		# Write beside the target and move into place, so a failed render never leaves a
		# truncated output behind.
		tmp="$(mktemp "${out}.XXXXXX")"
		if ! render_one "${header}" >"${tmp}"; then
			rm -f "${tmp}"
			return 1
		fi
		chmod 644 "${tmp}"
		mv "${tmp}" "${out}"
	done
}

# Define Function =check_all= — diff a fresh render against the committed outputs.
check_all() {
	local scratch entry rel
	local stale=0

	scratch="$(mktemp -d)"
	# shellcheck disable=SC2064 # expand now: scratch is local and gone when the trap fires
	trap "rm -rf '${scratch}'" EXIT

	render_all "${scratch}"

	for entry in "${output_map[@]}"; do
		rel="${entry#*:}"
		if [[ ! -f "${repo_dir}/${rel}" ]]; then
			echo "render.sh: missing output: ${rel}" >&2
			stale=1
		elif ! diff -u "${repo_dir}/${rel}" "${scratch}/${rel}" >&2; then
			echo "render.sh: stale output: ${rel}" >&2
			stale=1
		fi
	done

	if [[ "${stale}" -ne 0 ]]; then
		echo "render.sh: outputs differ from agents/; run agents/render.sh and commit the result" >&2
		return 1
	fi
	echo "render.sh: all outputs are current"
}

case "${1-}" in
	"")
		render_all "${repo_dir}"
		;;
	--check)
		check_all
		;;
	*)
		echo "usage: agents/render.sh [--check]" >&2
		exit 2
		;;
esac
