[tools]
bun = "latest"
go = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"
zig = "latest"

[settings]
minimum_release_age = "12h"

[settings.ruby]
compile = false
